model:
    keypoints_num: 17
    init_weights: True
    pretrained_path: ''
    input_size: 
        w: 288
        h: 384
    heatmap_size:
        w: 72
        h: 96
    margin_to_border: 1.15 # >=1
    
    ## use an extra mask module branch or only add a channel to
    mask_channel_num: 1

    only_add_mask_channel: false

    extra_mask_module: true
    extra_feature_flag: true
    
    booster_stacks: 1 # meta-booster nums
    boosting_requirement: 0.4

images_root_dir: '/home/public_dataset/coco/images/'
annotation_root_dir: '/home/public_dataset/coco/annotations/'
person_detection_results_path: '/home/public_dataset/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'

train:
    epoch_begin: 0
    epoch_end: 150
    lr: 0.001
    lr_step_size: 30
    lr_decay_gamma: 0.4
    batchsize: 64
    heatmap_peak_sigma_factor: 3
    aug_scale: 0.3
    aug_rotation: 40
    aug_flip: false
    augmentation: true

    #
    mask_loss_weight: 0.5

    

    
    
test:
    batchsize: 32
    bbox_score_threshold: 0.0

    confidence_threshold: 0.2
    oks_nms_threshold: 0.95

    ckpt: 'ckpt/pose_resnet_50_384x288.pth.tar'
