model:
    init_weights: True
    pretrained_path: ''

images_root_dir: '../data/coco/images/'
annotation_root_dir: '../data/coco/annotations/'
person_detection_results_path: '../data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'

train:
    epoch_begin: 0
    epoch_end: 100
    lr: 0.01
    batchsize: 64
    heatmap_peak_sigma_margin: 2.4

test:
    batchsize: 32
    bbox_score_threshold: 0.0

    confidence_threshold: 0.2
    oks_nms_threshold: 0.9

    ckpt: 'best_chpt.pt'
